apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: example.mutatingwebhook.com
    clientConfig:
      service:
        name: admission-webhook-example-svc
        namespace: ${NAMESPACE}
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    failurePolicy: Fail
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchExpressions:
      - key: webhooks-deployed
        operator: NotIn
        values: ["true","1"]