apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: example.validatingwebhook.com
    clientConfig:
      service:
        name: nginx-webhook-proxy
        namespace: ${NAMESPACE}
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchExpressions:
      - key: webhooks-deployed
        operator: NotIn
        values: ["true","1"]